export default {
  // Todo list actions types

  GET_TODO_LIST: 'GET_TODO_LIST',
  GET_TODO_LIST_REQUESTING: 'GET_TODO_LIST_REQUESTING',
  GET_TODO_LIST_SUCCESS: 'GET_TODO_LIST_SUCCESS',
  GET_TODO_LIST_ERROR: 'GET_TODO_LIST_ERROR',

  CREATE_TODO_LIST: 'CREATE_TODO_LIST',
  CREATE_TODO_LIST_REQUESTING: 'CREATE_TODO_LIST_REQUESTING',
  CREATE_TODO_LIST_SUCCESS: 'CREATE_TODO_LIST_SUCCESS',
  CREATE_TODO_LIST_ERROR: 'CREATE_TODO_LIST_ERROR',

  UPDATE_TODO_LIST: 'UPDATE_TODO_LIST',
  UPDATE_TODO_LIST_REQUESTING: 'UPDATE_TODO_LIST_REQUESTING',
  UPDATE_TODO_LIST_SUCCESS: 'UPDATE_TODO_LIST_SUCCESS',
  UPDATE_TODO_LIST_ERROR: 'UPDATE_TODO_LIST_ERROR',

  DELETE_TODO_LIST: 'DELETE_TODO_LIST',
  DELETE_TODO_LIST_REQUESTING: 'DELETE_TODO_LIST_REQUESTING',
  DELETE_TODO_LIST_SUCCESS: 'DELETE_TODO_LIST_SUCCESS',
  DELETE_TODO_LIST_ERROR: 'DELETE_TODO_LIST_ERROR',

  // Todo items actions types

  CREATE_TODO_ITEM: 'CREATE_TODO_ITEM',
  CREATE_TODO_ITEM_REQUESTING: 'CREATE_TODO_ITEM_REQUESTING',
  CREATE_TODO_ITEM_SUCCESS: 'CREATE_TODO_ITEM_SUCCESS',
  CREATE_TODO_ITEM_ERROR: 'CREATE_TODO_ITEM_ERROR',

  UPDATE_TODO_ITEM: 'UPDATE_TODO_ITEM',
  UPDATE_TODO_ITEM_REQUESTING: 'UPDATE_TODO_ITEM_REQUESTING',
  UPDATE_TODO_ITEM_SUCCESS: 'UPDATE_TODO_ITEM_SUCCESS',
  UPDATE_TODO_ITEM_ERROR: 'UPDATE_TODO_ITEM_ERROR',

  DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
  DELETE_TODO_ITEM_REQUESTING: 'DELETE_TODO_ITEM_REQUESTING',
  DELETE_TODO_ITEM_SUCCESS: 'DELETE_TODO_ITEM_SUCCESS',
  DELETE_TODO_ITEM_ERROR: 'DELETE_TODO_ITEM_ERROR'
}
