export default {
  GET_TODO_LIST: 'GET_TODO_LIST',
  GET_TODO_LIST_REQUESTING: 'GET_TODO_LIST_REQUESTING',
  GET_TODO_LIST_SUCCESS: 'GET_TODO_LIST_SUCCESS',
  GET_TODO_LIST_ERROR: 'GET_TODO_LIST_ERROR'
}